### ISSUE TITLE
I'm having trouble with installation.

### ISSUE THREAD

**Issue by pwongnak** [nandadorea/vetsyn#13]
I cannot install the package. I've followed the instruction but there were some errors as below:

> * installing *source* package 'vetsyn' ...
> ** R
> ** data
> *** moving datasets to lazyload DB
> ** inst
> ** tests
> ** preparing package for lazy loading
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   there is no package called 'lattice'
> ERROR: lazy loading failed for package 'vetsyn'

I already installed the 'lattice' package but it still didn't work. I'm new with installing packages from Github. My RStudio version is R-3.3.1 and I use Windows 7. Do you have any recommendation?

**Comment by pwongnak** [comment]
I repeated installing 'lattice' again and now it worked!! Case closed!! Thank you!!

**Comment by nandadorea** [comment]
THANKS, I was going to suggest that. Let me know if further issues/questiosn appear.
