### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by marcraemaekers** [nandadorea/vetsyn#7]
I got the following error message while trying to install the package:

> install_github("nandadorea/vetsyn")
> Downloading GitHub repo nandadorea/vetsyn@master
> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Timeout was reached

Thanks in advance for your help!

**Comment by nandadorea** [comment]
Hi, thank you for the interest in the package. This seems to be a problem
caused by some institutions' firewall - some firewalls will not let you
install directly from github. You can try downloading the zip file from
github and installing from the zip file. Or I can email you the zipfile if
you prefer - send me an email so that I can respond with teh zip file (
fernanda.dorea@sva.se).

**Comment by marcraemaekers** [comment]
I already tried the following:

> install.packages("C:/Users/marrae/Downloads/vetsyn-master.zip", repos = NULL, type = "win.binary")

But the package won't appear in the list of packages installed (RStudio, pane at the right-hand side)
(there's no error message)

**Comment by nandadorea** [comment]
Here is a solution that worked for me  (I got the same problem as you with
the zip):

 unzip the file you download (unzip manually)

Then run the following commands:

library(devtools)

install("(location of the unzipped file on your computer)/vetsyn-master")

library(vetsyn)

in my computer for instance this was:

require(devtools)

install("C:/Users/dorea.meyer/Downloads/vetsyn/vetsyn-master")

library(vetsyn)

Other have previously suggested:

install("C:/Data/vetsyn")

library(vetsyn)

(it really depends on where packages are being installed on your computer)

You may get some warning messages, but as long as you do not get an error,
all should work.

Please don't hesitate to write me if it still doesn't work.

**Comment by marcraemaekers** [comment]
Thanks, it seems to work now :-)
However, the vetsyn package will not appear in the package list. This means that each time Rstudio is started, I have to install it again? (using the "install" command)

**Comment by nandadorea** [comment]
I really hope not!!! Try opening RStudio again and just typing
library(vetsyn). If it does not work, let me know and I will continue
looking for a better solution.

Fernanda Dórea, BVM, MSc., PhD
Swedish Zoonosis Centre

Department of Disease Control and Epidemiology

NATIONAL VETERINARY INSTITUTE (SVA)
_phone. *+46 725 18 41 38
*e-mail._ fernanda.dorea@sva.se
_postal address._ SE-751 89 Uppsala, SWEDEN _webb._ www.sva.se
